# Generated by Django 4.0 on 2021-12-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0002_remove_image_image_remove_image_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
